### ISSUE TITLE
srs_format()

### ISSUE THREAD

**Issue by vanrein** [jichu4n/srslib#1]
Nice class.  I suppose the only thing missing to complete the abstraction of the SRS address format (current and potential future ones) is a test if an address is SRS-formatted.

One can simply try to reverse the mapping, but an exception is a bit harsh as an outcome.  For less exceptional use, such as sorting address for dealing with them either/other way, a simple boolean return value would be nicest.  Or a regular expression to match against.

**Comment by jichu4n** [comment]
Thanks - that's a great suggestion.

**Comment by jichu4n** [comment]
Added in 360e045a6b56031a67c1003fc94305f591066f53 and making a new release (0.1.3).

**Comment by vanrein** [comment]
Great work, Chuan!

-Rick
